name: Deploy BackEnd

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Pull the Fix Code 
        run: |
          cd Lab-Absen-JS-BackEnd/Lab-Absen-JS-BackEnd && git Pull origin main
          
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: Install Dependencies
        run: |
          npm install

      - name: Restart The pm2 and Start Applicaiton
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_PORT: ${{ secrets.DB_PORT }}
          PORT: ${{ secrets.PORT }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FRONT_END_ORIGINS: ${{ secrets.FRONT_END_ORIGINS }}

        run: pm2 restart 3
