name: Simple Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Create Symbolic Link to Target Directory
        run: ln -s /DataLab/absensi/cicdBackEnd $GITHUB_WORKSPACE
        
      - name: Check Out Code
        uses: actions/checkout@v2
        with:
          path: /DataLab/absensi/cicdBackEnd

      - name: Run a Simple Command
        run: echo "Hello, World!"
